<a href="https://colab.research.google.com/github/labib1910024/ECE_4246_Neural_Networks/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1. Creating NumPy Arrays
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)



1D Array:
[1 2 3]

2D Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# 2. Array Properties
print("\nArray Shape:", array_2d.shape)
print("Array Size:", array_2d.size)
print("Array Data Type:", array_2d.dtype)


Array Shape: (2, 3)
Array Size: 6
Array Data Type: int64


In [ ]:
# 3. Array Initialization
zeros = np.zeros((2, 3))  # 2x3 array of zeros
ones = np.ones((2, 3))  # 2x3 array of ones
random_values = np.random.rand(2, 3)  # 2x3 array of random values

print("\nZeros Array:")
print(zeros)

print("\nOnes Array:")
print(ones)

print("\nRandom Values Array:")
print(random_values)


Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]

Random Values Array:
[[0.01028168 0.0772549  0.34723863]
 [0.20431668 0.13626864 0.17305129]]


In [ ]:
# 4. Basic Operations
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

print("\nAddition:", array_a + array_b)
print("Subtraction:", array_a - array_b)
print("Multiplication:", array_a * array_b)
print("Division:", array_a / array_b)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [ ]:
# 5. Indexing and Slicing
array = np.array([10, 20, 30, 40, 50])

print("\nFirst Element:", array[0])
print("Last Element:", array[-1])
print("Sliced Array (index 1 to 3):", array[1:4])


First Element: 10
Last Element: 50
Sliced Array (index 1 to 3): [20 30 40]


In [ ]:
# 6. Mathematical Functions
angles = np.array([0, np.pi / 2, np.pi])

print("\nSine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))


Sine of angles: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine of angles: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [ ]:
# 7. Reshaping Arrays
reshaped_array = array_2d.reshape(3, 2)  # Change 2x3 array to 3x2
print("\nReshaped Array:")
print(reshaped_array)


Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# 8. Aggregation Functions
print("\nSum:", np.sum(array_2d))
print("Mean:", np.mean(array_2d))
print("Maximum:", np.max(array_2d))
print("Minimum:", np.min(array_2d))


Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1


In [ ]:
# 9. Broadcasting
scalar = 10
print("\nArray after adding scalar 10:")
print(array_2d + scalar)


Array after adding scalar 10:
[[11 12 13]
 [14 15 16]]
